AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda function with Python - Image Processing Function

Resources:
  ImageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: Processes images and user preferences (VULNERABLE - for testing only)
      MemorySize: 256
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /process
            Method: post
