AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda function demonstrating Python Subinterpreter Code Injection (CWE-94)

Resources:
  SubinterpreterFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      CodeUri: .
      Description: Executes user code in Python subinterpreter (VULNERABLE - for testing only)
      MemorySize: 256
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /execute
            Method: post
